name       : wabt
version    : 1.0.16
release    : 1
source     :
    - git|https://github.com/WebAssembly/wabt : 1.0.16
license    : Apache-2.0
component  : programming.tools
summary    : The WebAssembly Binary Toolkit
description: |
    WABT is a suite of tools for WebAssembly, including an dis/assembler, an interpreter, an objdump and strip utilities, etc.
rundeps    :
    - binaryen
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
