name       : wabt
version    : 1.0.20
release    : 2
source     :
    - https://github.com/WebAssembly/wabt/archive/1.0.20.tar.gz : 39def40e8719030e0d11b1abbd81427fb1731c0372fcb24e2baaea067acba66f
    - git|https://github.com/WebAssembly/wasm-c-api : 340fd9528cc3b26d22fe30ee1628c8c3f2b8c53b
license    : Apache-2.0
component  : programming.tools
summary    : The WebAssembly Binary Toolkit
description: |
    WABT is a suite of tools for WebAssembly, including an dis/assembler, an interpreter, an objdump and strip utilities, etc.
builddeps   :
    - binaryen-devel
setup      : |
    %patch -p1 < $pkgfiles/shared-wasm-rt-impl.patch
    cp -r $sources/wasm-c-api*/* third_party/wasm-c-api
    %cmake_ninja -DBUILD_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
